### ISSUE TITLE
[CHECKLIST] ETH2 light client on substrate using Rainbow Bridge

### ISSUE THREAD

**Issue by drewstone** [webb-tools/pallet-eth2-light-client#13]
# Overview
The main checklist for tracking what needs to get done to get this working.

## Components
1. Pallet
2. Types libraries (pulled from [lighthouse](https://github.com/webb-tools/lighthouse/tree/develop) / [rainbow-bridge](https://github.com/aurora-is-near/rainbow-bridge/)
3. Relayer service (pulled from [rainbow-bridge](https://github.com/aurora-is-near/rainbow-bridge/), using [webb-relayer](https://github.com/webb-tools/relayer))
4. Substrate client lib to interact with pallet ([subxt](https://github.com/paritytech/subxt))

## Tasks
- [x] Pallet scaffold
- [x] Pallet preliminary tests
- [x] Pallet `no_std/wasm` compilation in a substrate node runtime.
- [x] Implement `EthClientPalletTrait` for `EthClientPallet` (used to interface with pallet from relayer)
- [x] Integrate `Eth2SubstrateRelay` into a `LightClientRelayer` service using our relayer software.
- [ ] #22
- [x] Integration test relayer w/ local chain with `pallet-eth2-light-client` and subxt
- [x] Stable subxt, pallet, relayer dependencies
- [x] Pallet built and tested (continue updating against any changes to rainbow-bridge)
- [ ] Light client relayer crates building and tested (continue updating against any changes to eth2near-relay)

### Mock testing
Testing pallet in Substrate usually starts with unit tests against a mocked runtime. You can find the mocked runtime for the light client inside the `pallet` directly, https://github.com/webb-tools/pallet-eth2-light-client/blob/drew/relay/pallet/src/mock.rs. Specifically, the mocked runtime has a user-defined struct such as `Eth2Client` that can be manipulated to interact with the pallet's API directly.

For mocked testing, we would likely import the `eth2substrate-block-relay-rs` library into the `pallet` as a `dev-dependency` and then run the relayer in the pallet testing environment.

### Integration testing
Testing the pallet as an integration test will require integrating it into a full Substrate node. This testing setup will require running a live node adjacent to the relayer/tests of the relayer. Integration testing should only be done using [subxt](https://github.com/paritytech/subxt) which is the library for making remote calls to a Substrate chain.
