### ISSUE TITLE
[CHECKLIST] ETH2 Light-client re-integration/testing

### ISSUE THREAD

**Issue by drewstone** [webb-tools/pallet-eth2-light-client#69]
# Checklist
- [x] [BUG] Fix webb-proposals `no_std` issue.
- [x] [TASK] Update the `pallet-eth2-light-client` `eth2substrate-block-relay-rs`.
- [x] [TASK] Running it inside with Tangle (setting up configuration files)
- [x] [TASK] Update README
- [x] [TASK] (low-priority) Re-implement the `eth2substrate-block-relay-rs` w/ runtime-apis / RPCs / as a gadget.
- [x] https://github.com/webb-tools/pallet-eth2-light-client/issues/60
- [x] https://github.com/webb-tools/pallet-eth2-light-client/issues/54
- [x] https://github.com/webb-tools/pallet-eth2-light-client/issues/67
