### ISSUE TITLE
[TASK] Create verification pallet to verify tx proof

### ISSUE THREAD

**Issue by salman01zp** [webb-tools/pallet-eth2-light-client#79]
## Overview
Create a verification pallet that will verify the TX proofs and storage proofs we can look at some work done by GGx  chain here

https://github.com/ggxchain/transaction-receipt-relayer/pull/26/

## Task List
- [ ] Add verification pallet
- [ ] Add tests for storage proof
- [ ] Add tests for tx proof
